#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();


$config = yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/common/config/common.php',
    require __DIR__ . '/console/config/console.php'
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
