<?php

namespace common\components;

use common\services\Response;
use yii\web\ErrorHandler as baseErrorHandler;
use Yii;

class ErrorHandler extends baseErrorHandler
{

    public function handleError($code, $message, $file, $line)
    {
        var_dump($code, $message, $file, $line);
        die;

        return parent::handleError('Error', $code, $message, $file, $line); // TODO: Change the autogenerated stub
    }

    public function handleException($exception)
    {
        if (1 === 0) {
            Yii::error($exception->__toString(), 'error');
        } else if (0 === 1) {

        } else {


            Yii::error($exception->__toString(), 'error');
        }

        if (getenv('environment') === 'development') {
            $message = $exception->__toString();
        }
        Response::send(['message' => $message]);
    }
}
