<?php

namespace common\components;

use yii\helpers\Json;
use yii\web\ErrorHandler as baseErrorHandler;
use Yii;

class ErrorHandler extends baseErrorHandler {

//  public function handleError($code, $message, $file, $line)
//  {
//      var_dump($code, $message, $file, $line);die;
//      return parent::handleError('Error' ,$code, $message, $file, $line); // TODO: Change the autogenerated stub
//  }

  public function handleException($exception)
  {
      if ($exception instanceof \Exception) {
          Yii::error($exception->__toString(), 'error');
      }

      Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
      Yii::$app->response->data = Json::encode(['qwe' => 'qweqwe']);
      Yii::$app->response->send();
  }
}
